### ISSUE TITLE
It does not work on Steam Deck Beta

### ISSUE THREAD

**Issue by RedCatCorner** [ILadis/ts3-qs4sd#15]
Decky loader report: 

TypeError: plugin_export.default is not a function 
at PluginLoader. importReactPlugin (http://localhost: 1337/frontend/chunk-DPstxVl2. js: 7052: 56)
at async PluginLoader . importPlugin (http://localhost: 1337/frontend/chunk-DPstxVl2. js: 7052: 13)
at async Promise. all (index 2)
at async PluginLoader. loadPlugins (http://localhost: 1337/frontend/chunk-DPstxVl2. js: 6923: 9)

**Comment by ILadis** [comment]
This reads like a DeckyLoader issue and not an issue related to the TS3 plugin.

I've found this bug report over at DeckyLoader: https://github.com/SteamDeckHomebrew/decky-loader/issues/659

Seems like they fixed it already in one of their latest pre releases.

Please let me know if updating DeckyLoader fixes your issue.

**Comment by RedCatCorner** [comment]
Thanks Reply. 
It still doesn't work in v3.0.0-pre5

**Comment by ILadis** [comment]
I'm probably going to have some time during the weekend to look into this.

If you want to try something in the meantime: there's an unreleased version of the plugin available which fixed a similar bug (which was also related to the beta/unstable branch, see issue #14). The patched version can be downloaded from [here](https://github.com/ILadis/ts3-qs4sd/files/15358322/plugin.zip) (for more details see [this comment](https://github.com/ILadis/ts3-qs4sd/issues/14#issuecomment-2118409594)).

If this also fixes this issue I'm going to bring this to the official store asap.

**Comment by RedCatCorner** [comment]
It still doesn't work, and Decky loader report the same thing.

**Comment by ILadis** [comment]
I couldn't get Decky Loader to work on Steam Deck beta. To be sure I did the right thing: went to Settings on my Deck and then under System switched the "System Update Channel" to "Beta". After restarting and applying all updates I upgraded to Decky Loader "v3.0.0-pre5" and restarted my Deck again. After all that, the plugin icon didn't appear in the Quick Access menu.

Anything I did wrong to switch to Steam Deck Beta?

As I couldn't get Decky Loader to work with the latest Steam Deck Beta I wasn't able to reproduce the issue.

**Comment by TrainDoctor** [comment]
@ILadis please let me know if you still need support in getting decky running. Happy to help time willing.

**Comment by ILadis** [comment]
Thanks for offering help!

I switched back to the Steam Deck Beta update channel, but I am still unable to get Decky working. And by "not working" I mean that the plugin icon isn't showing up in the Quick Access menu.

I'm currently on this version (after applying all updates):
* OS Version: 3.6.8
* OS Build: 20240626.100
* Steam Version: 1722380543

I also downloaded and installed the latest Decky pre-release version [v3.0.0-pre5](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v3.0.0-pre5).

<details><summary>This is the output I get for <code>journalctl -u decky.service</code>.</summary>

```txt
Aug 06 13:16:49 steamdeck systemd[1016]: Started SteamDeck Plugin Loader.
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [main][WARNING]: decky is running as an unprivileged user, this is not officially supported and may cau>
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [selector_events][DEBUG]: Using selector: EpollSelector
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [loader][INFO]: plugin_path: /home/deck/.local/share/decky/plugins
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [updater][DEBUG]: current branch: 0
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [main][DEBUG]: Loading plugins
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [loader][INFO]: import plugins from /home/deck/.local/share/decky/plugins
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [loader][INFO]: found plugin: ts3-qs4sd
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [loader][INFO]: Loaded TS3 QuickAccess
Aug 06 13:16:50 steamdeck PluginLoader[5133]: [selector_events][DEBUG]: Using selector: EpollSelector
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [main][INFO]: Loading Decky frontend!
Aug 06 13:16:50 steamdeck PluginLoader[5126]: [localplatformlinux][INFO]: Restarting steamwebhelper
Aug 06 13:16:51 steamdeck PluginLoader[5126]: [injector][WARNING]: The Tab SharedJSContext socket has been disconnected while listening for messages.
Aug 06 13:16:51 steamdeck PluginLoader[5126]: [main][INFO]: CEF has disconnected...
Aug 06 13:16:51 steamdeck PluginLoader[5126]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Aug 06 13:16:56 steamdeck PluginLoader[5126]: [main][DEBUG]: Couldn't find GamepadUI tab, waiting...
Aug 06 13:17:00 steamdeck PluginLoader[5126]: [loader][INFO]: Hot reload enabled
Aug 06 13:17:01 steamdeck PluginLoader[5126]: [main][INFO]: Loading Decky frontend!
Aug 06 13:17:01 steamdeck PluginLoader[5126]: [main][DEBUG]: Page event: None
Aug 06 13:17:01 steamdeck PluginLoader[5126]: [main][DEBUG]: Page event: Page.windowOpen
Aug 06 13:17:21 steamdeck PluginLoader[5126]: [updater][DEBUG]: checking for updates
Aug 06 13:17:21 steamdeck PluginLoader[5126]: [updater][DEBUG]: current branch: 0
Aug 06 13:17:21 steamdeck PluginLoader[5126]: [updater][DEBUG]: release type: release
Aug 06 13:17:21 steamdeck PluginLoader[5126]: [updater][DEBUG]: determining release type to find, branch is 0
Aug 06 13:17:21 steamdeck PluginLoader[5126]: [updater][DEBUG]: release type: release
Aug 06 13:17:21 steamdeck PluginLoader[5126]: [updater][INFO]: Updated remote version information
Aug 06 13:18:05 steamdeck PluginLoader[5126]: [main][DEBUG]: Page event: Page.frameStartedLoading
...
```

The message "`Page event: Page.frameStartedLoading`" is then repeated endlessly.
</details>

I also inspected the `SharedJSContext` using Chromium on my development machine.  
The only suspicion thing I could see was this error that showed up in console:

```txt
Uncaught (in promise) Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Object.Ea (libraries~00299a408.js:2:479592)
    at t.useSyncExternalStore (libraries~00299a408.js:2:620142)
    at h (libraries~00299a408.js:2:289018)
    at w (libraries~00299a408.js:2:290491)
    at Object.Me (chunk~2dcc5aaf7.js?contenthash=312a9a07b3bf39e75772:1:8215499)
    at chunk-c9d41843.js:324:46
    at fakeRenderComponent (chunk-c9d41843.js:213:17)
    at chunk-c9d41843.js:324:13
    at findModuleChild (chunk-c10d7146.js:51:31)
    at chunk-c9d41843.js:319:19
```

Not sure if this is related to Decky.

As for installed Decky plugins: currently only my own plugin is installed (TS3).  
Also uninstalling my plugin and restarting Decky had no effect.

If you need any more information please let me know.

**Comment by TrainDoctor** [comment]
Do you have a password you use before you open your Steam Deck? Try disabling that PIN if that's the case.

**Comment by ILadis** [comment]
I'm not using a password or PIN on my Deck. I have auto login enabled so I'm signed in right after starting my Deck.

**Comment by TrainDoctor** [comment]
Go ahead and wipe your decky install via the . desktop installer and then re-install. This is an unfortunate but fascinating failure mode I've never seen before.

**Comment by ILadis** [comment]
This was actually a good suggestion. I have a somewhat customized Decky installation, so I went through every detail and found my mistake. The plugin icon is now showing up in the Quick Access menu.

I'm also getting the error message from the original post when launching into my plugin. Since I can now reproduce the issue I can start to investigate.

**Comment by ILadis** [comment]
I think I fixed the issue.

@RedCatCorner: Please try the latest [pre-release from here](https://github.com/ILadis/ts3-qs4sd/releases/tag/latest).  
If it's also working for you, I'm going to submit a pull request to get the fix to the store.

**Comment by ILadis** [comment]
I've already [opened a pull request](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/670) to get the fix to the official store. Please post a [testing report](https://wiki.deckbrew.xyz/en/user-guide/testing#submitting-a-test-report) over there.

**Comment by RedCatCorner** [comment]
This issue has been fixed! Thanks for your work!

**Comment by ILadis** [comment]
Hey @RedCatCorner, the fix is still not available in the official store. Please submit a [testing report](https://wiki.deckbrew.xyz/en/user-guide/testing#submitting-a-test-report) in the [pull request](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/670) to get the fix to production. Thanks!
